### ISSUE TITLE
rake webhook:set[<token>] does not seem to work properly in certain cases

### ISSUE THREAD

**Issue by thibauld** [solyaris/BOTServer#1]
Hi,

I just had to troubleshoot why my bot was not receiving any updates from telegram.
It happens that I was able to fix the problem by setting up the webhook _by hand_ with the following curl command:

---

curl -s -X POST https://api.telegram.org/bot<token>?url=myhost.com:8443

---

So unfortunately, I don't know what went wrong when I used rake webhook:set[<token>] but I am very sure this was the issue.

I am using a real certificate, I was thinking that maybe the pb could come from the fact that your code passes the certificate when setting up the webhook even though it does not have to because it is not a self-signed certificate ?

Anyway, I wanted to let you know !
Best

**Comment by solyarisoftware** [comment]
Hi @thibauld 

in facts I used just a self-signed certificate for my tests and your Hypotesis seems to me correct.
What's the error the rake webhooks report ?

BTW, the code is in facs a draft and contains some point to be reviewd (using thin in threaded mode or better use puma, etc.) 
unfortunately I'm bussy at work and I can't maintain as I Would,

Let  me know what you think about the architecture: make sense to dynamic dispatching the update method call ?

thanks
giorgio
